name: 🚀 Feature Request
description: Suggest a new feature or improvement
title: "[Feature Request]: "
labels: [enhancement]
assignees:
  - selefra-bot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a feature request! Please fill out the details below to help us understand your suggestion.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature you are requesting.
      placeholder: ex. "Add support for custom themes"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the feature, including any relevant use cases or scenarios.
      placeholder: "As a user, I would like to be able to..."
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Benefit
      description: Explain how this feature would benefit other users or improve the overall experience.
      placeholder: "This feature would make it easier for users to..."
    validations:
      required: true
  - type: select
    id: priority
    attributes:
      label: Priority
      description: Select the priority of this feature request.
      options:
        - label: Low
          value: Low
        - label: Medium
          value: Medium
        - label: High
          value: High
        - label: Critical
          value: Critical
      placeholder: Select a priority
    validations:
      required: true
  - type: checkbox
    id: notify-me
    attributes:
      label: Notification
      description: Check this box if you want to be notified of updates to this feature request.
      default: true
